### ISSUE TITLE
Error related to auto-encrypt-localhost

### ISSUE THREAD

**Issue by edgarasben** [small-tech/sitekit#1]
Getting an error when trying to run `npm run dev`:

```
ENOENT: no such file or directory, open '/Users/edgaras/.small-tech.org/auto-encrypt-localhost/localhost.pem'
Error: ENOENT: no such file or directory, open '/Users/edgaras/.small-tech.org/auto-encrypt-localhost/localhost.pem'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (/Users/edgaras/Documents/Sites/test-sitekit/svelte.config.cjs:10:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:192:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
```

**Comment by aral** [comment]
Sorry, left that in there by mistake before I realised SvelteKit cannot run an https dev server properly at the moment. Just removed it. If you try it again, it should work now. Please let me know if it doesn’t. (Just make sure you have Site.js installed too.)

**Comment by edgarasben** [comment]
It worked, thank you!
